title: My Awesome Site
description: A site with a new Jekyll theme
baseurl: "/"
url: "https://hakanakssy.github.io/cool_card_api/"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

